import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css"; // Adjust path if needed
import Navbar from "@/components/Navbar";
import PictureSection from "@/components/PictureSection";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <PictureSection />
        <Navbar />
        <main className="flex-1">{children}</main> {/* This makes the content grow */}
        <Footer />
      </body>
    </html>
  );
}
